#!/bin/bash -e
# set Zoneminder admin password and email alert address

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/zoneminder.py --password="$APP_PASS" --email="$APP_EMAIL"
